-- Cố tình để trống file này vì bảng attendance_change_logs
-- ở version 8 vốn dĩ không có foreign key constraints cho attendance_id.
-- Việc thêm lại constraint ở đây sẽ gây lỗi dữ liệu mồ côi khi rollback.
